### ISSUE TITLE
Doesn't properly support 'jsontext' in SQLite database

### ISSUE THREAD

**Issue by scraperdragon** [scraperwiki/dumptruck-web#1]
If you have a column of type 'jsontext' (and perhaps the text isn't JSON) then the API fails with 

```
"Error: "
```

if you reference that column with

```
select * from table
```

or

```
select malformed_column from table
```

**Comment by scraperdragon** [comment]
It might be worth turning off dumptruck-classic's nascent json support if we're not using it.

**Comment by pwaller** [comment]
I'm closing old issues so that we can pluck signal from the noise. Please reopen if you encounter this or believe it is important.
