### ISSUE TITLE
CPU spinning forever

### ISSUE THREAD

**Issue by frabcus** [scraperwiki/dumptruck-web#9]
I've seen processes spinning CPU for 20 hours of dumptruck-web.

I think it should have some absolute high level timeout where it gets killed.

**Comment by pwaller** [comment]
I think it's possible to construct this simply by making a pathological query against a large sqlite database with no useful indices.

We might consider moving dumptruck-web into the CGI sandbox and making them resource limited.

**Comment by pwaller** [comment]
Not observed as an issue in recent history.
